/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import org.example.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

}
